### ISSUE TITLE
EPIC: Add subcommands for all docker-compose subcommands

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/containers-sugar#44]
- [x] build              Build or rebuild services
- [x] #45
- [x] #46
- [x] down               Stop and remove resources
- [x] #47
- [x] exec               Execute a command in a running container
- [x] #48
- [x] #49
- [x] logs               View output from containers
- [x] #50
- [x] #51
- [x] #52
- [x] pull               Pull service images
- [x] #53
- [x] #54
- [x] #55
- [x] run                Run a one-off command
- #56 ~ deprecated
- [x] #57
- [x] stop               Stop services
- [x] #58
- [x] #59
- [x] up                 Create and start containers

**Comment by xmnlab** [comment]
completed by #77
